server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guan_wang?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    database: 0 # Redis数据库索引（默认为0）
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
    key:
      admin: 'ums:admin'
      resourceList: 'ums:resourceList'
    expire:
      common: 86400 # 24小时
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  mvc:
    servlet:
      load-on-startup: 1
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
  # 在线用户key# 在线用户key
  online-key: online-token-

# IP 本地解析
ip:
  local-parsing: true

secure:
  ignored:
    urls: #安全路径白名单
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
      - /admin/user
      - /file/download
      - /preview
      - /admin/code
      - /image/**
      - /aliyun/oss/getStsToken
      - /job/jobList
      - /newsSeries/list
      - /news/getAllNewsByType
      - /news/queryNewsContent/**
      - /news/getNewsSort/**
      - /prodSeries/listAll
      - /prod/getAllProdByType
      - /prod/queryContent/**
      - /prod/getRecommendProd
      - /history/allList
      - /intro/queryContent
      - /culture/list
      - /serviceIdea/listAll
      - /solutionSeries/listAll
      - /solutionSeries/list/withChildren
      - /question/getListByFirstLevel
      - /question/getQuestionListByType
      - /question/getQuestionHot
      - /question/addQuestionView/**
      - /message/addContent

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tQypUTDzwEmi8Hx1kqC # 访问身份验证中用到用户标识
    accessKeySecret: nhWgUzvNB6jlxTssOwfx1rGWyrsa1J # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: example-wang-oss # oss的存储空间
    roleArn: acs:ram::1008435655279290:role/ramosstest
    regionId: cn-hangzhou
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: test # 上传文件夹路径前缀




